before_script:
  - npm prune
  - npm install
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release

language: node_js
node_js:
  - "5.6.0"

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8.2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8.2
