before_script:
  - npm prune
  - npm install
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release

language: node_js
node_js:
  - "5.6.0"

sudo: false

cache:
  directories:
    - node_modules

compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
