before_install: npm install -g grunt-cli
before_script:
  - mysql -u root -e 'create database teamline_test'
  - npm prune
  - npm install
script:
  - grunt
  - npm run test:single
after_success:
  - npm run report-coverage

language: node_js
node_js:
  - "5.6.0"

cache:
  directories:
    - node_modules

# MySQL
services: mysql

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
